# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BeamDetection.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BeamDetection(object):
    def setupUi(self, BeamDetection):
        BeamDetection.setObjectName("BeamDetection")
        BeamDetection.resize(967, 374)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BeamDetection.sizePolicy().hasHeightForWidth())
        BeamDetection.setSizePolicy(sizePolicy)
        BeamDetection.setStyleSheet("background-color: rgb(80, 80, 80)")
        self.groupBox = QtWidgets.QGroupBox(BeamDetection)
        self.groupBox.setGeometry(QtCore.QRect(14, 14, 302, 346))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.OpenPort = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenPort.sizePolicy().hasHeightForWidth())
        self.OpenPort.setSizePolicy(sizePolicy)
        self.OpenPort.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.OpenPort.setObjectName("OpenPort")
        self.gridLayout_2.addWidget(self.OpenPort, 0, 0, 1, 1)
        self.ClosePort = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClosePort.sizePolicy().hasHeightForWidth())
        self.ClosePort.setSizePolicy(sizePolicy)
        self.ClosePort.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.ClosePort.setObjectName("ClosePort")
        self.gridLayout_2.addWidget(self.ClosePort, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.MessageTextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageTextBrowser.sizePolicy().hasHeightForWidth())
        self.MessageTextBrowser.setSizePolicy(sizePolicy)
        self.MessageTextBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.MessageTextBrowser.setObjectName("MessageTextBrowser")
        self.verticalLayout_2.addWidget(self.MessageTextBrowser)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.MoveUpside = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveUpside.sizePolicy().hasHeightForWidth())
        self.MoveUpside.setSizePolicy(sizePolicy)
        self.MoveUpside.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.MoveUpside.setObjectName("MoveUpside")
        self.gridLayout.addWidget(self.MoveUpside, 0, 0, 1, 1)
        self.MoveStop = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveStop.sizePolicy().hasHeightForWidth())
        self.MoveStop.setSizePolicy(sizePolicy)
        self.MoveStop.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.MoveStop.setObjectName("MoveStop")
        self.gridLayout.addWidget(self.MoveStop, 0, 1, 1, 1)
        self.upsideFrame = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upsideFrame.sizePolicy().hasHeightForWidth())
        self.upsideFrame.setSizePolicy(sizePolicy)
        self.upsideFrame.setMinimumSize(QtCore.QSize(30, 30))
        self.upsideFrame.setStyleSheet("background-color: rgb(10, 10, 10)")
        self.upsideFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upsideFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upsideFrame.setObjectName("upsideFrame")
        self.gridLayout.addWidget(self.upsideFrame, 0, 2, 1, 1)
        self.MoveDownside = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveDownside.sizePolicy().hasHeightForWidth())
        self.MoveDownside.setSizePolicy(sizePolicy)
        self.MoveDownside.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.MoveDownside.setObjectName("MoveDownside")
        self.gridLayout.addWidget(self.MoveDownside, 1, 0, 1, 1)
        self.Save = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save.sizePolicy().hasHeightForWidth())
        self.Save.setSizePolicy(sizePolicy)
        self.Save.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.Save.setObjectName("Save")
        self.gridLayout.addWidget(self.Save, 1, 1, 1, 1)
        self.downsideFrame = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downsideFrame.sizePolicy().hasHeightForWidth())
        self.downsideFrame.setSizePolicy(sizePolicy)
        self.downsideFrame.setMinimumSize(QtCore.QSize(30, 30))
        self.downsideFrame.setStyleSheet("background-color: rgb(10, 10, 10)")
        self.downsideFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downsideFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downsideFrame.setObjectName("downsideFrame")
        self.gridLayout.addWidget(self.downsideFrame, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(BeamDetection)
        self.groupBox_2.setGeometry(QtCore.QRect(325, 14, 628, 346))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BeamCurveFrame = QtWidgets.QFrame(self.groupBox_2)
        self.BeamCurveFrame.setMinimumSize(QtCore.QSize(600, 300))
        self.BeamCurveFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BeamCurveFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BeamCurveFrame.setObjectName("BeamCurveFrame")
        self.verticalLayout.addWidget(self.BeamCurveFrame)

        self.retranslateUi(BeamDetection)
        QtCore.QMetaObject.connectSlotsByName(BeamDetection)

    def retranslateUi(self, BeamDetection):
        _translate = QtCore.QCoreApplication.translate
        BeamDetection.setWindowTitle(_translate("BeamDetection", "束流探测"))
        self.groupBox.setTitle(_translate("BeamDetection", "控制电机"))
        self.OpenPort.setText(_translate("BeamDetection", "打开串口"))
        self.ClosePort.setText(_translate("BeamDetection", "关闭串口"))
        self.MoveUpside.setText(_translate("BeamDetection", "向上"))
        self.MoveStop.setText(_translate("BeamDetection", "停止"))
        self.MoveDownside.setText(_translate("BeamDetection", "向下"))
        self.Save.setText(_translate("BeamDetection", "导出数据"))
        self.groupBox_2.setTitle(_translate("BeamDetection", "束流探测曲线"))

