# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainSerial.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1434, 809)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(80, 80, 80)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.checkButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkButton.sizePolicy().hasHeightForWidth())
        self.checkButton.setSizePolicy(sizePolicy)
        self.checkButton.setAcceptDrops(False)
        self.checkButton.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.checkButton.setCheckable(False)
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout_4.addWidget(self.checkButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.checkMessageTextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkMessageTextBrowser.sizePolicy().hasHeightForWidth())
        self.checkMessageTextBrowser.setSizePolicy(sizePolicy)
        self.checkMessageTextBrowser.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkMessageTextBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.checkMessageTextBrowser.setObjectName("checkMessageTextBrowser")
        self.verticalLayout.addWidget(self.checkMessageTextBrowser)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.velocitySpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocitySpinBox_2.sizePolicy().hasHeightForWidth())
        self.velocitySpinBox_2.setSizePolicy(sizePolicy)
        self.velocitySpinBox_2.setMinimumSize(QtCore.QSize(20, 20))
        self.velocitySpinBox_2.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.velocitySpinBox_2.setMaximum(2000.0)
        self.velocitySpinBox_2.setSingleStep(100.0)
        self.velocitySpinBox_2.setObjectName("velocitySpinBox_2")
        self.gridLayout_2.addWidget(self.velocitySpinBox_2, 1, 1, 1, 1)
        self.accelerationSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelerationSpinBox_1.sizePolicy().hasHeightForWidth())
        self.accelerationSpinBox_1.setSizePolicy(sizePolicy)
        self.accelerationSpinBox_1.setMinimumSize(QtCore.QSize(20, 20))
        self.accelerationSpinBox_1.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.accelerationSpinBox_1.setMaximum(2000.0)
        self.accelerationSpinBox_1.setSingleStep(100.0)
        self.accelerationSpinBox_1.setObjectName("accelerationSpinBox_1")
        self.gridLayout_2.addWidget(self.accelerationSpinBox_1, 0, 3, 1, 1)
        self.velocityLabel_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_4.sizePolicy().hasHeightForWidth())
        self.velocityLabel_4.setSizePolicy(sizePolicy)
        self.velocityLabel_4.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_4.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_4.setObjectName("velocityLabel_4")
        self.gridLayout_2.addWidget(self.velocityLabel_4, 1, 2, 1, 1)
        self.velocityLabel_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_2.sizePolicy().hasHeightForWidth())
        self.velocityLabel_2.setSizePolicy(sizePolicy)
        self.velocityLabel_2.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_2.setObjectName("velocityLabel_2")
        self.gridLayout_2.addWidget(self.velocityLabel_2, 0, 2, 1, 1)
        self.velocityLabel_1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_1.sizePolicy().hasHeightForWidth())
        self.velocityLabel_1.setSizePolicy(sizePolicy)
        self.velocityLabel_1.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_1.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_1.setObjectName("velocityLabel_1")
        self.gridLayout_2.addWidget(self.velocityLabel_1, 0, 0, 1, 1)
        self.velocitySpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocitySpinBox_1.sizePolicy().hasHeightForWidth())
        self.velocitySpinBox_1.setSizePolicy(sizePolicy)
        self.velocitySpinBox_1.setMinimumSize(QtCore.QSize(20, 20))
        self.velocitySpinBox_1.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.velocitySpinBox_1.setMaximum(2000.0)
        self.velocitySpinBox_1.setSingleStep(100.0)
        self.velocitySpinBox_1.setObjectName("velocitySpinBox_1")
        self.gridLayout_2.addWidget(self.velocitySpinBox_1, 0, 1, 1, 1)
        self.velocityLabel_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_3.sizePolicy().hasHeightForWidth())
        self.velocityLabel_3.setSizePolicy(sizePolicy)
        self.velocityLabel_3.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_3.setObjectName("velocityLabel_3")
        self.gridLayout_2.addWidget(self.velocityLabel_3, 1, 0, 1, 1)
        self.backwardDelay4SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backwardDelay4SpinBox.sizePolicy().hasHeightForWidth())
        self.backwardDelay4SpinBox.setSizePolicy(sizePolicy)
        self.backwardDelay4SpinBox.setMinimumSize(QtCore.QSize(20, 20))
        self.backwardDelay4SpinBox.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.backwardDelay4SpinBox.setObjectName("backwardDelay4SpinBox")
        self.gridLayout_2.addWidget(self.backwardDelay4SpinBox, 5, 3, 1, 1)
        self.velocityLabel_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_7.sizePolicy().hasHeightForWidth())
        self.velocityLabel_7.setSizePolicy(sizePolicy)
        self.velocityLabel_7.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_7.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_7.setObjectName("velocityLabel_7")
        self.gridLayout_2.addWidget(self.velocityLabel_7, 3, 0, 1, 1)
        self.velocitySpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocitySpinBox_4.sizePolicy().hasHeightForWidth())
        self.velocitySpinBox_4.setSizePolicy(sizePolicy)
        self.velocitySpinBox_4.setMinimumSize(QtCore.QSize(20, 20))
        self.velocitySpinBox_4.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.velocitySpinBox_4.setMaximum(2000.0)
        self.velocitySpinBox_4.setSingleStep(100.0)
        self.velocitySpinBox_4.setObjectName("velocitySpinBox_4")
        self.gridLayout_2.addWidget(self.velocitySpinBox_4, 3, 1, 1, 1)
        self.accelerationSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelerationSpinBox_2.sizePolicy().hasHeightForWidth())
        self.accelerationSpinBox_2.setSizePolicy(sizePolicy)
        self.accelerationSpinBox_2.setMinimumSize(QtCore.QSize(20, 20))
        self.accelerationSpinBox_2.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.accelerationSpinBox_2.setMaximum(2000.0)
        self.accelerationSpinBox_2.setSingleStep(100.0)
        self.accelerationSpinBox_2.setObjectName("accelerationSpinBox_2")
        self.gridLayout_2.addWidget(self.accelerationSpinBox_2, 1, 3, 1, 1)
        self.velocityLabel_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_10.sizePolicy().hasHeightForWidth())
        self.velocityLabel_10.setSizePolicy(sizePolicy)
        self.velocityLabel_10.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_10.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_10.setObjectName("velocityLabel_10")
        self.gridLayout_2.addWidget(self.velocityLabel_10, 4, 2, 1, 1)
        self.velocitySpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocitySpinBox_5.sizePolicy().hasHeightForWidth())
        self.velocitySpinBox_5.setSizePolicy(sizePolicy)
        self.velocitySpinBox_5.setMinimumSize(QtCore.QSize(20, 20))
        self.velocitySpinBox_5.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.velocitySpinBox_5.setMaximum(2000.0)
        self.velocitySpinBox_5.setSingleStep(100.0)
        self.velocitySpinBox_5.setObjectName("velocitySpinBox_5")
        self.gridLayout_2.addWidget(self.velocitySpinBox_5, 4, 1, 1, 1)
        self.velocityLabel_9 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_9.sizePolicy().hasHeightForWidth())
        self.velocityLabel_9.setSizePolicy(sizePolicy)
        self.velocityLabel_9.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_9.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_9.setObjectName("velocityLabel_9")
        self.gridLayout_2.addWidget(self.velocityLabel_9, 4, 0, 1, 1)
        self.accelerationSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelerationSpinBox_5.sizePolicy().hasHeightForWidth())
        self.accelerationSpinBox_5.setSizePolicy(sizePolicy)
        self.accelerationSpinBox_5.setMinimumSize(QtCore.QSize(20, 20))
        self.accelerationSpinBox_5.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.accelerationSpinBox_5.setMaximum(2000.0)
        self.accelerationSpinBox_5.setSingleStep(100.0)
        self.accelerationSpinBox_5.setObjectName("accelerationSpinBox_5")
        self.gridLayout_2.addWidget(self.accelerationSpinBox_5, 4, 3, 1, 1)
        self.periodsSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodsSpinBox.sizePolicy().hasHeightForWidth())
        self.periodsSpinBox.setSizePolicy(sizePolicy)
        self.periodsSpinBox.setMinimumSize(QtCore.QSize(20, 20))
        self.periodsSpinBox.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.periodsSpinBox.setMaximum(1000.0)
        self.periodsSpinBox.setObjectName("periodsSpinBox")
        self.gridLayout_2.addWidget(self.periodsSpinBox, 5, 1, 1, 1)
        self.accelerationSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelerationSpinBox_3.sizePolicy().hasHeightForWidth())
        self.accelerationSpinBox_3.setSizePolicy(sizePolicy)
        self.accelerationSpinBox_3.setMinimumSize(QtCore.QSize(20, 20))
        self.accelerationSpinBox_3.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.accelerationSpinBox_3.setMaximum(2000.0)
        self.accelerationSpinBox_3.setSingleStep(100.0)
        self.accelerationSpinBox_3.setObjectName("accelerationSpinBox_3")
        self.gridLayout_2.addWidget(self.accelerationSpinBox_3, 2, 3, 1, 1)
        self.accelerationSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelerationSpinBox_4.sizePolicy().hasHeightForWidth())
        self.accelerationSpinBox_4.setSizePolicy(sizePolicy)
        self.accelerationSpinBox_4.setMinimumSize(QtCore.QSize(20, 20))
        self.accelerationSpinBox_4.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.accelerationSpinBox_4.setMaximum(2000.0)
        self.accelerationSpinBox_4.setSingleStep(100.0)
        self.accelerationSpinBox_4.setObjectName("accelerationSpinBox_4")
        self.gridLayout_2.addWidget(self.accelerationSpinBox_4, 3, 3, 1, 1)
        self.velocityLabel_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_5.sizePolicy().hasHeightForWidth())
        self.velocityLabel_5.setSizePolicy(sizePolicy)
        self.velocityLabel_5.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_5.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_5.setObjectName("velocityLabel_5")
        self.gridLayout_2.addWidget(self.velocityLabel_5, 2, 0, 1, 1)
        self.velocityLabel_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_8.sizePolicy().hasHeightForWidth())
        self.velocityLabel_8.setSizePolicy(sizePolicy)
        self.velocityLabel_8.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_8.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_8.setObjectName("velocityLabel_8")
        self.gridLayout_2.addWidget(self.velocityLabel_8, 3, 2, 1, 1)
        self.periodsLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodsLabel.sizePolicy().hasHeightForWidth())
        self.periodsLabel.setSizePolicy(sizePolicy)
        self.periodsLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.periodsLabel.setObjectName("periodsLabel")
        self.gridLayout_2.addWidget(self.periodsLabel, 5, 0, 1, 1)
        self.backwardDelay4Label = QtWidgets.QLabel(self.groupBox)
        self.backwardDelay4Label.setObjectName("backwardDelay4Label")
        self.gridLayout_2.addWidget(self.backwardDelay4Label, 5, 2, 1, 1)
        self.velocityLabel_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityLabel_6.sizePolicy().hasHeightForWidth())
        self.velocityLabel_6.setSizePolicy(sizePolicy)
        self.velocityLabel_6.setMinimumSize(QtCore.QSize(20, 20))
        self.velocityLabel_6.setTextFormat(QtCore.Qt.AutoText)
        self.velocityLabel_6.setObjectName("velocityLabel_6")
        self.gridLayout_2.addWidget(self.velocityLabel_6, 2, 2, 1, 1)
        self.velocitySpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocitySpinBox_3.sizePolicy().hasHeightForWidth())
        self.velocitySpinBox_3.setSizePolicy(sizePolicy)
        self.velocitySpinBox_3.setMinimumSize(QtCore.QSize(20, 20))
        self.velocitySpinBox_3.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.velocitySpinBox_3.setMaximum(2000.0)
        self.velocitySpinBox_3.setSingleStep(100.0)
        self.velocitySpinBox_3.setObjectName("velocitySpinBox_3")
        self.gridLayout_2.addWidget(self.velocitySpinBox_3, 2, 1, 1, 1)
        self.backwardDelay3Label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backwardDelay3Label.sizePolicy().hasHeightForWidth())
        self.backwardDelay3Label.setSizePolicy(sizePolicy)
        self.backwardDelay3Label.setObjectName("backwardDelay3Label")
        self.gridLayout_2.addWidget(self.backwardDelay3Label, 6, 0, 1, 1)
        self.backwardDelay3SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backwardDelay3SpinBox.sizePolicy().hasHeightForWidth())
        self.backwardDelay3SpinBox.setSizePolicy(sizePolicy)
        self.backwardDelay3SpinBox.setMinimumSize(QtCore.QSize(20, 20))
        self.backwardDelay3SpinBox.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.backwardDelay3SpinBox.setObjectName("backwardDelay3SpinBox")
        self.gridLayout_2.addWidget(self.backwardDelay3SpinBox, 6, 1, 1, 1)
        self.backwardDelay2Label = QtWidgets.QLabel(self.groupBox)
        self.backwardDelay2Label.setObjectName("backwardDelay2Label")
        self.gridLayout_2.addWidget(self.backwardDelay2Label, 6, 2, 1, 1)
        self.backwardDelay2SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backwardDelay2SpinBox.sizePolicy().hasHeightForWidth())
        self.backwardDelay2SpinBox.setSizePolicy(sizePolicy)
        self.backwardDelay2SpinBox.setMinimumSize(QtCore.QSize(20, 20))
        self.backwardDelay2SpinBox.setStyleSheet("font: 14pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.backwardDelay2SpinBox.setObjectName("backwardDelay2SpinBox")
        self.gridLayout_2.addWidget(self.backwardDelay2SpinBox, 6, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.velocitySetCurveFrame = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocitySetCurveFrame.sizePolicy().hasHeightForWidth())
        self.velocitySetCurveFrame.setSizePolicy(sizePolicy)
        self.velocitySetCurveFrame.setMinimumSize(QtCore.QSize(461, 271))
        self.velocitySetCurveFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.velocitySetCurveFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.velocitySetCurveFrame.setObjectName("velocitySetCurveFrame")
        self.verticalLayout.addWidget(self.velocitySetCurveFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.completeCycleNumberLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completeCycleNumberLabel.sizePolicy().hasHeightForWidth())
        self.completeCycleNumberLabel.setSizePolicy(sizePolicy)
        self.completeCycleNumberLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.completeCycleNumberLabel.setObjectName("completeCycleNumberLabel")
        self.horizontalLayout.addWidget(self.completeCycleNumberLabel)
        self.completeCycleNumberLcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.completeCycleNumberLcdNumber.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(90, 90, 90)")
        self.completeCycleNumberLcdNumber.setObjectName("completeCycleNumberLcdNumber")
        self.horizontalLayout.addWidget(self.completeCycleNumberLcdNumber)
        self.ScanProgressBar = QtWidgets.QProgressBar(self.groupBox)
        self.ScanProgressBar.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.ScanProgressBar.setProperty("value", 24)
        self.ScanProgressBar.setObjectName("ScanProgressBar")
        self.horizontalLayout.addWidget(self.ScanProgressBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.confirmParameterButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmParameterButton.sizePolicy().hasHeightForWidth())
        self.confirmParameterButton.setSizePolicy(sizePolicy)
        self.confirmParameterButton.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.confirmParameterButton.setObjectName("confirmParameterButton")
        self.gridLayout.addWidget(self.confirmParameterButton, 0, 0, 1, 1)
        self.startScanButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startScanButton.sizePolicy().hasHeightForWidth())
        self.startScanButton.setSizePolicy(sizePolicy)
        self.startScanButton.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(90, 90, 90);\n"
"font: 10pt \"Adobe Devanagari\";")
        self.startScanButton.setObjectName("startScanButton")
        self.gridLayout.addWidget(self.startScanButton, 0, 1, 1, 1)
        self.changeParameterButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeParameterButton.sizePolicy().hasHeightForWidth())
        self.changeParameterButton.setSizePolicy(sizePolicy)
        self.changeParameterButton.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.changeParameterButton.setObjectName("changeParameterButton")
        self.gridLayout.addWidget(self.changeParameterButton, 1, 0, 1, 1)
        self.stopScanButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopScanButton.sizePolicy().hasHeightForWidth())
        self.stopScanButton.setSizePolicy(sizePolicy)
        self.stopScanButton.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.stopScanButton.setObjectName("stopScanButton")
        self.gridLayout.addWidget(self.stopScanButton, 1, 1, 1, 1)
        self.MoveInside = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveInside.sizePolicy().hasHeightForWidth())
        self.MoveInside.setSizePolicy(sizePolicy)
        self.MoveInside.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.MoveInside.setObjectName("MoveInside")
        self.gridLayout.addWidget(self.MoveInside, 2, 0, 1, 1)
        self.Stop = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop.sizePolicy().hasHeightForWidth())
        self.Stop.setSizePolicy(sizePolicy)
        self.Stop.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.Stop.setObjectName("Stop")
        self.gridLayout.addWidget(self.Stop, 2, 1, 1, 1)
        self.MoveOutside = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveOutside.sizePolicy().hasHeightForWidth())
        self.MoveOutside.setSizePolicy(sizePolicy)
        self.MoveOutside.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.MoveOutside.setObjectName("MoveOutside")
        self.gridLayout.addWidget(self.MoveOutside, 3, 0, 1, 1)
        self.MoveToOriginalLocation = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveToOriginalLocation.sizePolicy().hasHeightForWidth())
        self.MoveToOriginalLocation.setSizePolicy(sizePolicy)
        self.MoveToOriginalLocation.setStyleSheet("font: 10pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.MoveToOriginalLocation.setObjectName("MoveToOriginalLocation")
        self.gridLayout.addWidget(self.MoveToOriginalLocation, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outsideFrameLabel = QtWidgets.QLabel(self.groupBox_2)
        self.outsideFrameLabel.setObjectName("outsideFrameLabel")
        self.horizontalLayout_2.addWidget(self.outsideFrameLabel)
        self.outsideFrame = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outsideFrame.sizePolicy().hasHeightForWidth())
        self.outsideFrame.setSizePolicy(sizePolicy)
        self.outsideFrame.setMinimumSize(QtCore.QSize(40, 40))
        self.outsideFrame.setStyleSheet("background-color: rgb(10, 10, 10)")
        self.outsideFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outsideFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outsideFrame.setObjectName("outsideFrame")
        self.horizontalLayout_2.addWidget(self.outsideFrame)
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.outsideFrame_3 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outsideFrame_3.sizePolicy().hasHeightForWidth())
        self.outsideFrame_3.setSizePolicy(sizePolicy)
        self.outsideFrame_3.setMinimumSize(QtCore.QSize(40, 40))
        self.outsideFrame_3.setStyleSheet("background-color: rgb(10, 10, 10)")
        self.outsideFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outsideFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outsideFrame_3.setObjectName("outsideFrame_3")
        self.horizontalLayout_2.addWidget(self.outsideFrame_3)
        spacerItem1 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.insideFrame_2 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insideFrame_2.sizePolicy().hasHeightForWidth())
        self.insideFrame_2.setSizePolicy(sizePolicy)
        self.insideFrame_2.setMinimumSize(QtCore.QSize(40, 40))
        self.insideFrame_2.setStyleSheet("background-color: rgb(10, 10, 10)")
        self.insideFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.insideFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.insideFrame_2.setObjectName("insideFrame_2")
        self.horizontalLayout_2.addWidget(self.insideFrame_2)
        spacerItem2 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.insideFrame = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insideFrame.sizePolicy().hasHeightForWidth())
        self.insideFrame.setSizePolicy(sizePolicy)
        self.insideFrame.setMinimumSize(QtCore.QSize(40, 40))
        self.insideFrame.setStyleSheet("background-color: rgb(10, 10, 10)")
        self.insideFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.insideFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.insideFrame.setObjectName("insideFrame")
        self.horizontalLayout_2.addWidget(self.insideFrame)
        self.insideFrameLabel = QtWidgets.QLabel(self.groupBox_2)
        self.insideFrameLabel.setObjectName("insideFrameLabel")
        self.horizontalLayout_2.addWidget(self.insideFrameLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.realtimeVelocityCurveFrame = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.realtimeVelocityCurveFrame.sizePolicy().hasHeightForWidth())
        self.realtimeVelocityCurveFrame.setSizePolicy(sizePolicy)
        self.realtimeVelocityCurveFrame.setMinimumSize(QtCore.QSize(801, 250))
        self.realtimeVelocityCurveFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.realtimeVelocityCurveFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.realtimeVelocityCurveFrame.setObjectName("realtimeVelocityCurveFrame")
        self.verticalLayout_2.addWidget(self.realtimeVelocityCurveFrame)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sendToMotorMessageTextBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendToMotorMessageTextBrowser.sizePolicy().hasHeightForWidth())
        self.sendToMotorMessageTextBrowser.setSizePolicy(sizePolicy)
        self.sendToMotorMessageTextBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.sendToMotorMessageTextBrowser.setObjectName("sendToMotorMessageTextBrowser")
        self.verticalLayout_3.addWidget(self.sendToMotorMessageTextBrowser)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.userToMotorMessageBrowser = QtWidgets.QLabel(self.groupBox_3)
        self.userToMotorMessageBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.userToMotorMessageBrowser.setObjectName("userToMotorMessageBrowser")
        self.horizontalLayout_3.addWidget(self.userToMotorMessageBrowser)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.sendToSensorMessageTextBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendToSensorMessageTextBrowser.sizePolicy().hasHeightForWidth())
        self.sendToSensorMessageTextBrowser.setSizePolicy(sizePolicy)
        self.sendToSensorMessageTextBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.sendToSensorMessageTextBrowser.setObjectName("sendToSensorMessageTextBrowser")
        self.verticalLayout_3.addWidget(self.sendToSensorMessageTextBrowser)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.userToSensorMessageBrowser = QtWidgets.QLabel(self.groupBox_3)
        self.userToSensorMessageBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.userToSensorMessageBrowser.setObjectName("userToSensorMessageBrowser")
        self.horizontalLayout_5.addWidget(self.userToSensorMessageBrowser)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.sendToSensorMessageTextBrowser.raise_()
        self.sendToMotorMessageTextBrowser.raise_()
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.receivedMotorMessageTextBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivedMotorMessageTextBrowser.sizePolicy().hasHeightForWidth())
        self.receivedMotorMessageTextBrowser.setSizePolicy(sizePolicy)
        self.receivedMotorMessageTextBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.receivedMotorMessageTextBrowser.setObjectName("receivedMotorMessageTextBrowser")
        self.verticalLayout_4.addWidget(self.receivedMotorMessageTextBrowser)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.motorToUserMessageBrowser = QtWidgets.QLabel(self.groupBox_4)
        self.motorToUserMessageBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.motorToUserMessageBrowser.setObjectName("motorToUserMessageBrowser")
        self.horizontalLayout_7.addWidget(self.motorToUserMessageBrowser)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.receivedSensorMessageTextBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivedSensorMessageTextBrowser.sizePolicy().hasHeightForWidth())
        self.receivedSensorMessageTextBrowser.setSizePolicy(sizePolicy)
        self.receivedSensorMessageTextBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.receivedSensorMessageTextBrowser.setObjectName("receivedSensorMessageTextBrowser")
        self.verticalLayout_4.addWidget(self.receivedSensorMessageTextBrowser)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.sensorToUserMessageBrowser = QtWidgets.QLabel(self.groupBox_4)
        self.sensorToUserMessageBrowser.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.sensorToUserMessageBrowser.setObjectName("sensorToUserMessageBrowser")
        self.horizontalLayout_6.addWidget(self.sensorToUserMessageBrowser)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1434, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setTabletTracking(False)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menug = QtWidgets.QMenu(self.menubar)
        self.menug.setObjectName("menug")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDefaultPort = QtWidgets.QAction(MainWindow)
        self.actionDefaultPort.setObjectName("actionDefaultPort")
        self.actionSerial = QtWidgets.QAction(MainWindow)
        self.actionSerial.setObjectName("actionSerial")
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setObjectName("actionLog")
        self.actionAboutme = QtWidgets.QAction(MainWindow)
        self.actionAboutme.setObjectName("actionAboutme")
        self.actionScan = QtWidgets.QAction(MainWindow)
        self.actionScan.setObjectName("actionScan")
        self.menu.addAction(self.actionSerial)
        self.menu.addAction(self.actionScan)
        self.menu_2.addAction(self.actionLog)
        self.menug.addAction(self.actionAboutme)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menug.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gearshift Scanning Control V1.2"))
        self.groupBox.setTitle(_translate("MainWindow", "扫描设置"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">检测设备状态</span></p></body></html>"))
        self.checkButton.setText(_translate("MainWindow", "CHECK"))
        self.velocityLabel_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间2加速度</span></p></body></html>"))
        self.velocityLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间1加速度</span></p></body></html>"))
        self.velocityLabel_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间1速度</span></p></body></html>"))
        self.velocityLabel_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间2速度</span></p></body></html>"))
        self.velocityLabel_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间4速度</span></p></body></html>"))
        self.velocityLabel_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间5加速度</span></p></body></html>"))
        self.velocityLabel_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间5速度</span></p></body></html>"))
        self.velocityLabel_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间3速度</span></p></body></html>"))
        self.velocityLabel_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间4加速度</span></p></body></html>"))
        self.periodsLabel.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">扫描周期</span></p></body></html>"))
        self.backwardDelay4Label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">反向延迟4/s</span></p></body></html>"))
        self.velocityLabel_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">区间3加速度</span></p></body></html>"))
        self.backwardDelay3Label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">反向延迟3/s</span></p></body></html>"))
        self.backwardDelay2Label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">反向延迟2/s</span></p></body></html>"))
        self.completeCycleNumberLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">已完成周期</span></p></body></html>"))
        self.confirmParameterButton.setText(_translate("MainWindow", "确认参数"))
        self.startScanButton.setText(_translate("MainWindow", "开始扫描"))
        self.changeParameterButton.setText(_translate("MainWindow", "修改参数"))
        self.stopScanButton.setText(_translate("MainWindow", "结束并关闭串口"))
        self.MoveInside.setText(_translate("MainWindow", "向内"))
        self.Stop.setText(_translate("MainWindow", "停止"))
        self.MoveOutside.setText(_translate("MainWindow", "向外"))
        self.MoveToOriginalLocation.setText(_translate("MainWindow", "复位"))
        self.groupBox_2.setTitle(_translate("MainWindow", "状态"))
        self.outsideFrameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">外侧</span></p></body></html>"))
        self.insideFrameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">内侧</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">上位机&gt;&gt;&gt;电机：</span></p></body></html>"))
        self.userToMotorMessageBrowser.setText(_translate("MainWindow", "<html><head/><body><p>0</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bytes</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">上位机&gt;&gt;&gt;传感器：</span></p></body></html>"))
        self.userToSensorMessageBrowser.setText(_translate("MainWindow", "<html><head/><body><p>0</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bytes</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "接收"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">电机&gt;&gt;&gt;上位机：</span></p></body></html>"))
        self.motorToUserMessageBrowser.setText(_translate("MainWindow", "<html><head/><body><p>0</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bytes</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">传感器&gt;&gt;&gt;上位机：</span></p></body></html>"))
        self.sensorToUserMessageBrowser.setText(_translate("MainWindow", "<html><head/><body><p>0</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bytes</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menug.setTitle(_translate("MainWindow", "关于"))
        self.actionDefaultPort.setText(_translate("MainWindow", "载入默认设置"))
        self.actionSerial.setText(_translate("MainWindow", "手动配置扫描串口参数"))
        self.actionLog.setText(_translate("MainWindow", "导出工作日志"))
        self.actionAboutme.setText(_translate("MainWindow", "关于本软件"))
        self.actionScan.setText(_translate("MainWindow", "束流探测扫描设置"))

