# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SerialPortSet.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SerialPortSet(object):
    def setupUi(self, SerialPortSet):
        SerialPortSet.setObjectName("SerialPortSet")
        SerialPortSet.resize(764, 340)
        SerialPortSet.setStyleSheet("background-color: rgb(80, 80, 80)")
        self.saveSerialConfigButton = QtWidgets.QPushButton(SerialPortSet)
        self.saveSerialConfigButton.setGeometry(QtCore.QRect(310, 290, 143, 41))
        self.saveSerialConfigButton.setStyleSheet("font: 11pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.saveSerialConfigButton.setObjectName("saveSerialConfigButton")
        self.groupBox = QtWidgets.QGroupBox(SerialPortSet)
        self.groupBox.setGeometry(QtCore.QRect(13, 13, 240, 275))
        self.groupBox.setMinimumSize(QtCore.QSize(240, 275))
        self.groupBox.setStyleSheet("font: 9pt \"Adobe Devanagari\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chooseMotorParity = QtWidgets.QLabel(self.groupBox)
        self.chooseMotorParity.setObjectName("chooseMotorParity")
        self.gridLayout.addWidget(self.chooseMotorParity, 3, 0, 1, 1)
        self.chooseMotorParitycomboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseMotorParitycomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorParitycomboBox.setEditable(False)
        self.chooseMotorParitycomboBox.setObjectName("chooseMotorParitycomboBox")
        self.gridLayout.addWidget(self.chooseMotorParitycomboBox, 3, 1, 1, 1)
        self.chooseMotorPortcomboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseMotorPortcomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorPortcomboBox.setEditable(False)
        self.chooseMotorPortcomboBox.setObjectName("chooseMotorPortcomboBox")
        self.gridLayout.addWidget(self.chooseMotorPortcomboBox, 0, 1, 1, 1)
        self.chooseMotorBaudrate = QtWidgets.QLabel(self.groupBox)
        self.chooseMotorBaudrate.setObjectName("chooseMotorBaudrate")
        self.gridLayout.addWidget(self.chooseMotorBaudrate, 1, 0, 1, 1)
        self.chooseMotorByteSize = QtWidgets.QLabel(self.groupBox)
        self.chooseMotorByteSize.setObjectName("chooseMotorByteSize")
        self.gridLayout.addWidget(self.chooseMotorByteSize, 2, 0, 1, 1)
        self.chooseMotorBaudratecomboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseMotorBaudratecomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorBaudratecomboBox.setEditable(False)
        self.chooseMotorBaudratecomboBox.setObjectName("chooseMotorBaudratecomboBox")
        self.gridLayout.addWidget(self.chooseMotorBaudratecomboBox, 1, 1, 1, 1)
        self.chooseMotorByteSizecomboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseMotorByteSizecomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorByteSizecomboBox.setEditable(False)
        self.chooseMotorByteSizecomboBox.setObjectName("chooseMotorByteSizecomboBox")
        self.gridLayout.addWidget(self.chooseMotorByteSizecomboBox, 2, 1, 1, 1)
        self.chooseMotorStopBytescomboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseMotorStopBytescomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorStopBytescomboBox.setEditable(False)
        self.chooseMotorStopBytescomboBox.setObjectName("chooseMotorStopBytescomboBox")
        self.gridLayout.addWidget(self.chooseMotorStopBytescomboBox, 4, 1, 1, 1)
        self.chooseMotorPort = QtWidgets.QLabel(self.groupBox)
        self.chooseMotorPort.setObjectName("chooseMotorPort")
        self.gridLayout.addWidget(self.chooseMotorPort, 0, 0, 1, 1)
        self.chooseMotorStopBytes = QtWidgets.QLabel(self.groupBox)
        self.chooseMotorStopBytes.setObjectName("chooseMotorStopBytes")
        self.gridLayout.addWidget(self.chooseMotorStopBytes, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox_4 = QtWidgets.QGroupBox(SerialPortSet)
        self.groupBox_4.setGeometry(QtCore.QRect(262, 13, 240, 275))
        self.groupBox_4.setStyleSheet("font: 9pt \"Adobe Devanagari\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.chooseSensorPort = QtWidgets.QLabel(self.groupBox_4)
        self.chooseSensorPort.setObjectName("chooseSensorPort")
        self.gridLayout_4.addWidget(self.chooseSensorPort, 0, 0, 1, 1)
        self.chooseSensorPortcomboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.chooseSensorPortcomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseSensorPortcomboBox.setEditable(False)
        self.chooseSensorPortcomboBox.setObjectName("chooseSensorPortcomboBox")
        self.gridLayout_4.addWidget(self.chooseSensorPortcomboBox, 0, 1, 1, 1)
        self.chooseSensorBaudratecomboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.chooseSensorBaudratecomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseSensorBaudratecomboBox.setEditable(False)
        self.chooseSensorBaudratecomboBox.setObjectName("chooseSensorBaudratecomboBox")
        self.gridLayout_4.addWidget(self.chooseSensorBaudratecomboBox, 1, 1, 1, 1)
        self.chooseSensorByteSize = QtWidgets.QLabel(self.groupBox_4)
        self.chooseSensorByteSize.setObjectName("chooseSensorByteSize")
        self.gridLayout_4.addWidget(self.chooseSensorByteSize, 2, 0, 1, 1)
        self.chooseSensorBaudrate = QtWidgets.QLabel(self.groupBox_4)
        self.chooseSensorBaudrate.setObjectName("chooseSensorBaudrate")
        self.gridLayout_4.addWidget(self.chooseSensorBaudrate, 1, 0, 1, 1)
        self.chooseSensorByteSizecomboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.chooseSensorByteSizecomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseSensorByteSizecomboBox.setEditable(False)
        self.chooseSensorByteSizecomboBox.setObjectName("chooseSensorByteSizecomboBox")
        self.gridLayout_4.addWidget(self.chooseSensorByteSizecomboBox, 2, 1, 1, 1)
        self.chooseSensorStopBytes = QtWidgets.QLabel(self.groupBox_4)
        self.chooseSensorStopBytes.setObjectName("chooseSensorStopBytes")
        self.gridLayout_4.addWidget(self.chooseSensorStopBytes, 4, 0, 1, 1)
        self.chooseSensorParity = QtWidgets.QLabel(self.groupBox_4)
        self.chooseSensorParity.setObjectName("chooseSensorParity")
        self.gridLayout_4.addWidget(self.chooseSensorParity, 3, 0, 1, 1)
        self.chooseSensorStopBytescomboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.chooseSensorStopBytescomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseSensorStopBytescomboBox.setEditable(False)
        self.chooseSensorStopBytescomboBox.setObjectName("chooseSensorStopBytescomboBox")
        self.gridLayout_4.addWidget(self.chooseSensorStopBytescomboBox, 4, 1, 1, 1)
        self.chooseSensorParitycomboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.chooseSensorParitycomboBox.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseSensorParitycomboBox.setEditable(False)
        self.chooseSensorParitycomboBox.setObjectName("chooseSensorParitycomboBox")
        self.gridLayout_4.addWidget(self.chooseSensorParitycomboBox, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.groupBox_6 = QtWidgets.QGroupBox(SerialPortSet)
        self.groupBox_6.setGeometry(QtCore.QRect(511, 13, 240, 275))
        self.groupBox_6.setStyleSheet("font: 9pt \"Adobe Devanagari\";")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.chooseMotorPortcomboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.chooseMotorPortcomboBox_3.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorPortcomboBox_3.setEditable(False)
        self.chooseMotorPortcomboBox_3.setObjectName("chooseMotorPortcomboBox_3")
        self.gridLayout_6.addWidget(self.chooseMotorPortcomboBox_3, 0, 1, 1, 1)
        self.chooseMotorByteSize_3 = QtWidgets.QLabel(self.groupBox_6)
        self.chooseMotorByteSize_3.setObjectName("chooseMotorByteSize_3")
        self.gridLayout_6.addWidget(self.chooseMotorByteSize_3, 2, 0, 1, 1)
        self.chooseMotorPort_3 = QtWidgets.QLabel(self.groupBox_6)
        self.chooseMotorPort_3.setObjectName("chooseMotorPort_3")
        self.gridLayout_6.addWidget(self.chooseMotorPort_3, 0, 0, 1, 1)
        self.chooseMotorBaudratecomboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.chooseMotorBaudratecomboBox_3.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorBaudratecomboBox_3.setEditable(False)
        self.chooseMotorBaudratecomboBox_3.setObjectName("chooseMotorBaudratecomboBox_3")
        self.gridLayout_6.addWidget(self.chooseMotorBaudratecomboBox_3, 1, 1, 1, 1)
        self.chooseMotorStopBytes_3 = QtWidgets.QLabel(self.groupBox_6)
        self.chooseMotorStopBytes_3.setObjectName("chooseMotorStopBytes_3")
        self.gridLayout_6.addWidget(self.chooseMotorStopBytes_3, 4, 0, 1, 1)
        self.chooseMotorStopBytescomboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.chooseMotorStopBytescomboBox_3.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorStopBytescomboBox_3.setEditable(False)
        self.chooseMotorStopBytescomboBox_3.setObjectName("chooseMotorStopBytescomboBox_3")
        self.gridLayout_6.addWidget(self.chooseMotorStopBytescomboBox_3, 4, 1, 1, 1)
        self.chooseMotorBaudrate_3 = QtWidgets.QLabel(self.groupBox_6)
        self.chooseMotorBaudrate_3.setObjectName("chooseMotorBaudrate_3")
        self.gridLayout_6.addWidget(self.chooseMotorBaudrate_3, 1, 0, 1, 1)
        self.chooseMotorParity_3 = QtWidgets.QLabel(self.groupBox_6)
        self.chooseMotorParity_3.setObjectName("chooseMotorParity_3")
        self.gridLayout_6.addWidget(self.chooseMotorParity_3, 3, 0, 1, 1)
        self.chooseMotorParitycomboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.chooseMotorParitycomboBox_3.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorParitycomboBox_3.setEditable(False)
        self.chooseMotorParitycomboBox_3.setObjectName("chooseMotorParitycomboBox_3")
        self.gridLayout_6.addWidget(self.chooseMotorParitycomboBox_3, 3, 1, 1, 1)
        self.chooseMotorByteSizecomboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.chooseMotorByteSizecomboBox_3.setStyleSheet("font: 12pt \"Adobe Devanagari\";\n"
"background-color: rgb(90, 90, 90)")
        self.chooseMotorByteSizecomboBox_3.setEditable(False)
        self.chooseMotorByteSizecomboBox_3.setObjectName("chooseMotorByteSizecomboBox_3")
        self.gridLayout_6.addWidget(self.chooseMotorByteSizecomboBox_3, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)

        self.retranslateUi(SerialPortSet)
        self.chooseMotorPortcomboBox.setCurrentIndex(-1)
        self.chooseSensorPortcomboBox.setCurrentIndex(-1)
        self.chooseMotorPortcomboBox_3.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(SerialPortSet)

    def retranslateUi(self, SerialPortSet):
        _translate = QtCore.QCoreApplication.translate
        SerialPortSet.setWindowTitle(_translate("SerialPortSet", "扫描串口设置"))
        self.saveSerialConfigButton.setText(_translate("SerialPortSet", "保存配置文件"))
        self.groupBox.setTitle(_translate("SerialPortSet", "基板扫描电机串口设置"))
        self.chooseMotorParity.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">校验位</span></p></body></html>"))
        self.chooseMotorBaudrate.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">波特率</span></p></body></html>"))
        self.chooseMotorByteSize.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">数据位</span></p></body></html>"))
        self.chooseMotorPort.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">选择串口</span></p></body></html>"))
        self.chooseMotorStopBytes.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">停止位</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("SerialPortSet", "接近传感器串口设置"))
        self.chooseSensorPort.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">选择串口</span></p></body></html>"))
        self.chooseSensorByteSize.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">数据位</span></p></body></html>"))
        self.chooseSensorBaudrate.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">波特率</span></p></body></html>"))
        self.chooseSensorStopBytes.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">停止位</span></p></body></html>"))
        self.chooseSensorParity.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">校验位</span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("SerialPortSet", "束流探测电机串口设置"))
        self.chooseMotorByteSize_3.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">数据位</span></p></body></html>"))
        self.chooseMotorPort_3.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">选择串口</span></p></body></html>"))
        self.chooseMotorStopBytes_3.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">停止位</span></p></body></html>"))
        self.chooseMotorBaudrate_3.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">波特率</span></p></body></html>"))
        self.chooseMotorParity_3.setText(_translate("SerialPortSet", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">校验位</span></p></body></html>"))

